
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - my-datavolume:/var/lib/postgres
volumes:
  my-datavolume:
