
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    env_file:
      - .env.dev
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_volume: