
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - db


  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  celery:
    restart: always
    build:
      context: .
    command: celery -A innotter worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq
      - app
volumes:
  postgres_volume:
