
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - my-app:/app

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
  my-app: