# Generated by Django 4.1.1 on 2022-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='innoapp.tag'),
        ),
    ]
